export const DIMENSION = {
  MIN_WIDTH_ZERO: '0',
  TEXTAREA_MIN_HEIGHT: '100px',
  TITLE_CONTAINER_MAX_WIDTH: '1000px',
  WORKSPACE_TYPE_BUBBLE_MIN_WIDTH: '140px',
  SPLASH_LOGO_SIZE: '120px',
  SPLASH_LOGO_HEIGHT_VH: '15.6vh',
  LOADING_BAR_HEIGHT: '4px',
  SECURITY_NOTICE_WIDTH: '360px',
  SEARCH_INPUT_WIDTH: '300px',
  DROPDOWN_BUTTON_MIN_WIDTH: '180px',
  DROPDOWN_WIDTH: '120px',
  EMPTY_STATE_SUBTITLE_MAX_WIDTH: '400px',
  DOT_SIZE: '4px',
} as const

