export const DIMENSION = {
  TEXTAREA_MIN_HEIGHT: '100px',
  TITLE_CONTAINER_MAX_WIDTH: '1000px',
  WORKSPACE_TYPE_BUBBLE_MIN_WIDTH: '140px',
  SPLASH_LOGO_SIZE: '120px',
  LOADING_BAR_HEIGHT: '4px',
} as const

