export const OPACITY = {
  ZERO: 0,
  OVERLAY: 0.5,
  BUTTON_GRADIENT_START: 0.5,
  BUTTON_GRADIENT_END: 0,
  SHADOW: 0.2,
  NAVBAR_SHADOW: 0.05,
  SLIDER_SHADOW: 0.3,
  DISABLED: 0.4,
  LOADING_OVERLAY: 0.9,
  FULL: 1,
} as const

