export const TRANSITION_DURATION = {
  FAST: '0.2s',
  NORMAL: '0.3s',
  SLOW: '0.5s',
  VERY_SLOW: '1s',
} as const

export const TRANSITION_EASING = {
  EASE: 'ease',
  EASE_IN: 'ease-in',
  EASE_OUT: 'ease-out',
  EASE_IN_OUT: 'ease-in-out',
} as const

export const TRANSITION = {
  FAST_EASE: `${TRANSITION_DURATION.FAST} ${TRANSITION_EASING.EASE}`,
  NORMAL_EASE: `${TRANSITION_DURATION.NORMAL} ${TRANSITION_EASING.EASE}`,
  SLOW_EASE: `${TRANSITION_DURATION.SLOW} ${TRANSITION_EASING.EASE}`,
  FAST_EASE_IN: `${TRANSITION_DURATION.FAST} ${TRANSITION_EASING.EASE_IN}`,
  FAST_EASE_OUT: `${TRANSITION_DURATION.FAST} ${TRANSITION_EASING.EASE_OUT}`,
  FAST_EASE_IN_OUT: `${TRANSITION_DURATION.FAST} ${TRANSITION_EASING.EASE_IN_OUT}`,
  NORMAL_EASE_IN: `${TRANSITION_DURATION.NORMAL} ${TRANSITION_EASING.EASE_IN}`,
  NORMAL_EASE_OUT: `${TRANSITION_DURATION.NORMAL} ${TRANSITION_EASING.EASE_OUT}`,
  NORMAL_EASE_IN_OUT: `${TRANSITION_DURATION.NORMAL} ${TRANSITION_EASING.EASE_IN_OUT}`,
} as const

